title: "Chinmaya Ramalaya"
email: "bvadmin@chinmayaramalaya.org"
description: "Chinmaya Ramalaya in Harleysville, PA. Rooted in Vedanta, Nurturing Character, Serving Community."
baseurl: "/chinmayaramalaya"
url: "https://vajrang-b.github.io"
source: docs
markdown: kramdown
highlighter: rouge
exclude:
  - .venv
  - validators
  - crawler.py
  - report_generator.py
  - validate.py
  - reports
  - README.md
